# This sets up a live NAV development environment in Docker containers.
#
# Defaults NAV to a container with Python 2. If you want to work with NAV in a
# Python 3 environment, add a `docker-compose.override.yml` that sets the
# dockerfile to Dockerfile3, like so:
#
# version: '2'
# services:
#   nav:
#     build:
#       dockerfile: Dockerfile3
version: '2'
services:
  nav:
    build: .
    environment:
      - NONAVSTART=0  # Set to 1 to disable startup of NAV backend processes when container starts
      - PGHOST=postgres
      - PGDATABASE=nav
      - PGUSER=postgres
    ports:
      - "80:80"
    volumes:
      - .:/source
    depends_on:
      - postgres
  postgres:
    image: "postgres:9.4"
    ports:
      - "54320:5432"  # also set this port in db.conf
  graphite:
    build: ./tools/docker/graphite
    ports:
      - "8000:8000"
      - "2003:2003/udp" # expose udp port as it was setup in graphite.conf
      - "2003:2003/tcp"
      - "2004:2004"
    volumes:
      - ./python/nav/etc/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./python/nav/etc/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf

  # Add a service to continuously rebuild the Sphinx documentation if the doc
  # directory is modified:
  docbuild:
    build: .
    volumes_from:
      - nav
    command: /source/tools/docker/doc-watch.sh
